Repository RSE-Sheffield/RSE-Sheffield.github.io, pull requests merged in 2024-12, with the labels that each got.

#845 Home page improvements
  _config.yml
  _includes/events_list_top10.html
  _includes/post_list_prev10.html
  _layouts/home.html
  assets/css/custom.css
Labels: enhancement, aesthetics

#844 Add December 2024 newsletter draft
  _newsletters/2024-12-06-newsletter.md
Labels: Newsletter

#856 chore: Adds .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: enhancement

#857 training: Add links to "Missing Semester" resources
  .git-blame-ignore-revs
  pages/training/programming/index.md
Labels: enhancement
